"""add poker session tables

Revision ID: 691c8a94da79
Revises: a1b2c3d4e5f6
Create Date: 2026-02-05 18:28:25.000648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '691c8a94da79'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poker_estimate_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('story_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('min_estimate', sa.Integer(), nullable=True),
    sa.Column('max_estimate', sa.Integer(), nullable=True),
    sa.Column('average_estimate', sa.Float(), nullable=True),
    sa.Column('suggested_estimate', sa.Integer(), nullable=True),
    sa.Column('accepted_estimate', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_poker_sessions_story_id', 'poker_estimate_sessions', ['story_id'], unique=False)
    op.create_index('idx_poker_sessions_user_id', 'poker_estimate_sessions', ['user_id'], unique=False)
    op.create_table('poker_persona_estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('persona_name', sa.String(length=100), nullable=False),
    sa.Column('persona_role', sa.String(length=100), nullable=False),
    sa.Column('estimate_points', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['poker_estimate_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_id')
    )
    op.create_index('idx_poker_estimates_session_id', 'poker_persona_estimates', ['session_id'], unique=False)
    op.drop_index(op.f('idx_story_deps_depends_on'), table_name='story_dependencies')
    op.drop_index(op.f('idx_story_deps_story_id'), table_name='story_dependencies')
    op.drop_table('story_dependencies')
    op.drop_index(op.f('idx_sprint_items_entity'), table_name='sprint_plan_items')
    op.drop_index(op.f('idx_sprint_items_plan_id'), table_name='sprint_plan_items')
    op.drop_table('sprint_plan_items')
    op.drop_index(op.f('idx_deferred_plan_id'), table_name='sprint_deferred_items')
    op.drop_table('sprint_deferred_items')
    op.drop_index(op.f('idx_attachment_epic_id'), table_name='epic_attachments')
    op.drop_index(op.f('idx_attachment_user_id'), table_name='epic_attachments')
    op.drop_table('epic_attachments')
    op.drop_index(op.f('idx_prd_epic'), table_name='prd_documents')
    op.drop_index(op.f('idx_prd_user'), table_name='prd_documents')
    op.drop_table('prd_documents')
    op.drop_index(op.f('idx_sprint_plans_status'), table_name='sprint_plans')
    op.drop_index(op.f('idx_sprint_plans_user_id'), table_name='sprint_plans')
    op.drop_table('sprint_plans')
    op.drop_index(op.f('idx_moscow_entity'), table_name='moscow_scores')
    op.drop_table('moscow_scores')
    op.drop_index(op.f('idx_poker_entity'), table_name='poker_estimates')
    op.drop_table('poker_estimates')
    op.drop_index(op.f('idx_rice_entity'), table_name='rice_scores')
    op.drop_index(op.f('idx_rice_total'), table_name='rice_scores')
    op.drop_table('rice_scores')
    op.drop_index(op.f('idx_otp_email_verified'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_email'), table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    op.create_foreign_key(None, 'bugs', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_model_health_user_provider'), table_name='model_health_metrics')
    op.create_index('idx_model_health_user_provider_model', 'model_health_metrics', ['user_id', 'provider', 'model_name'], unique=False)
    op.alter_column('persona_generation_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('persona_generation_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'persona_generation_settings', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('personas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'personas', 'epics', ['epic_id'], ['epic_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'personas', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_story_versions', 'user_stories', ['story_id'], ['story_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'verification_tokens', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.drop_constraint(None, 'user_story_versions', type_='foreignkey')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.alter_column('personas', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('personas', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'persona_generation_settings', type_='foreignkey')
    op.alter_column('persona_generation_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('persona_generation_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('idx_model_health_user_provider_model', table_name='model_health_metrics')
    op.create_index(op.f('idx_model_health_user_provider'), 'model_health_metrics', ['user_id', 'provider'], unique=False)
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.create_table('password_reset_otps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_otps_pkey'))
    )
    op.create_index(op.f('ix_password_reset_otps_email'), 'password_reset_otps', ['email'], unique=False)
    op.create_index(op.f('idx_otp_email_verified'), 'password_reset_otps', ['email', 'verified'], unique=False)
    op.create_table('rice_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reach', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('effort', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("entity_type::text = ANY (ARRAY['feature'::character varying, 'story'::character varying, 'bug'::character varying]::text[])", name=op.f('ck_rice_entity_type')),
    sa.CheckConstraint('effort >= 0.5::double precision AND effort <= 10::double precision', name=op.f('ck_rice_effort_range')),
    sa.CheckConstraint('reach >= 1 AND reach <= 10', name=op.f('ck_rice_reach_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('rice_scores_pkey')),
    sa.UniqueConstraint('score_id', name=op.f('rice_scores_score_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_rice_total'), 'rice_scores', ['total'], unique=False)
    op.create_index(op.f('idx_rice_entity'), 'rice_scores', ['entity_type', 'entity_id'], unique=False)
    op.create_table('poker_estimates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('persona_estimates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw_average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('needs_breakdown', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('overall_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('poker_estimates_pkey')),
    sa.UniqueConstraint('estimate_id', name=op.f('poker_estimates_estimate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_poker_entity'), 'poker_estimates', ['entity_type', 'entity_id'], unique=False)
    op.create_table('moscow_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("category::text = ANY (ARRAY['must_have'::character varying, 'should_have'::character varying, 'could_have'::character varying, 'wont_have'::character varying]::text[])", name=op.f('ck_moscow_category')),
    sa.CheckConstraint("entity_type::text = ANY (ARRAY['epic'::character varying, 'feature'::character varying]::text[])", name=op.f('ck_moscow_entity_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('moscow_scores_pkey')),
    sa.UniqueConstraint('score_id', name=op.f('moscow_scores_score_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_moscow_entity'), 'moscow_scores', ['entity_type', 'entity_id'], unique=False)
    op.create_table('sprint_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sprint_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('sprint_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sprint_length_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('standalone_reservation_pct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('standalone_points_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('epic_scoped_points_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buffer_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_epic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sprint_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('explainability', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_plans_pkey')),
    sa.UniqueConstraint('plan_id', name=op.f('sprint_plans_plan_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sprint_plans_user_id'), 'sprint_plans', ['user_id'], unique=False)
    op.create_index(op.f('idx_sprint_plans_status'), 'sprint_plans', ['status'], unique=False)
    op.create_table('prd_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prd_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('epic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('generation_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prd_documents_pkey')),
    sa.UniqueConstraint('prd_id', name=op.f('prd_documents_prd_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_prd_user'), 'prd_documents', ['user_id'], unique=False)
    op.create_index(op.f('idx_prd_epic'), 'prd_documents', ['epic_id'], unique=False)
    op.create_table('epic_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attachment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('epic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_content_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extraction_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extraction_error', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('include_in_ai_context', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("extraction_status::text = ANY (ARRAY['pending'::character varying, 'success'::character varying, 'failed'::character varying, 'partial'::character varying]::text[])", name=op.f('ck_attachment_extraction_status')),
    sa.CheckConstraint('file_size <= 10485760', name=op.f('ck_attachment_max_file_size')),
    sa.PrimaryKeyConstraint('id', name=op.f('epic_attachments_pkey')),
    sa.UniqueConstraint('attachment_id', name=op.f('epic_attachments_attachment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_attachment_user_id'), 'epic_attachments', ['user_id'], unique=False)
    op.create_index(op.f('idx_attachment_epic_id'), 'epic_attachments', ['epic_id'], unique=False)
    op.create_table('sprint_deferred_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deferred_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('story_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_standalone', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('epic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('feature_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('deferral_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('deferral_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blocking_entity_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sprint_plans.plan_id'], name=op.f('sprint_deferred_items_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_deferred_items_pkey')),
    sa.UniqueConstraint('deferred_id', name=op.f('sprint_deferred_items_deferred_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_deferred_plan_id'), 'sprint_deferred_items', ['plan_id'], unique=False)
    op.create_table('sprint_plan_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('story_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_standalone', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('epic_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('epic_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('feature_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('feature_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('moscow_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rice_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sequence_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selection_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sprint_plans.plan_id'], name=op.f('sprint_plan_items_plan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_plan_items_pkey')),
    sa.UniqueConstraint('item_id', name=op.f('sprint_plan_items_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sprint_items_plan_id'), 'sprint_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('idx_sprint_items_entity'), 'sprint_plan_items', ['entity_type', 'entity_id'], unique=False)
    op.create_table('story_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dependency_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('depends_on_story_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('story_dependencies_pkey')),
    sa.UniqueConstraint('dependency_id', name=op.f('story_dependencies_dependency_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_story_deps_story_id'), 'story_dependencies', ['story_id'], unique=False)
    op.create_index(op.f('idx_story_deps_depends_on'), 'story_dependencies', ['depends_on_story_id'], unique=False)
    op.drop_index('idx_poker_estimates_session_id', table_name='poker_persona_estimates')
    op.drop_table('poker_persona_estimates')
    op.drop_index('idx_poker_sessions_user_id', table_name='poker_estimate_sessions')
    op.drop_index('idx_poker_sessions_story_id', table_name='poker_estimate_sessions')
    op.drop_table('poker_estimate_sessions')
    # ### end Alembic commands ###
