import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { 
  Loader2, FileText, Download, Copy, Check, RefreshCw,
  ChevronRight, Sparkles, BookOpen
} from 'lucide-react';
import { epicAPI, featureAPI } from '@/api';

const PRDGenerator = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [epics, setEpics] = useState([]);
  const [selectedEpic, setSelectedEpic] = useState('');
  const [epicData, setEpicData] = useState(null);
  const [features, setFeatures] = useState([]);
  const [prdContent, setPrdContent] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    loadEpics();
  }, []);

  useEffect(() => {
    if (selectedEpic) {
      loadEpicData();
    }
  }, [selectedEpic]);

  const loadEpics = async () => {
    try {
      const response = await epicAPI.list();
      setEpics(response.data?.epics || []);
    } catch (error) {
      console.error('Failed to load epics:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadEpicData = async () => {
    if (!selectedEpic) return;
    
    setLoading(true);
    try {
      const [epicRes, featuresRes] = await Promise.all([
        epicAPI.get(selectedEpic),
        featureAPI.listForEpic(selectedEpic),
      ]);
      
      setEpicData(epicRes.data);
      setFeatures(featuresRes.data || []);
      
      // Generate PRD content
      generatePRD(epicRes.data, featuresRes.data || []);
    } catch (error) {
      console.error('Failed to load epic data:', error);
    } finally {
      setLoading(false);
    }
  };

  const generatePRD = (epic, featuresList) => {
    const now = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    const content = `# Product Requirements Document (PRD)

## Document Information
- **Product**: ${epic.title}
- **Version**: 1.0
- **Date**: ${now}
- **Status**: ${epic.stage?.replace('_', ' ').toUpperCase() || 'DRAFT'}

---

## 1. Executive Summary

### 1.1 Problem Statement
${epic.problem_statement || '_Not yet defined_'}

### 1.2 Product Vision
${epic.vision || '_Not yet defined_'}

### 1.3 Target Users
${epic.target_users || '_Not yet defined_'}

---

## 2. Goals & Objectives

### 2.1 Desired Outcomes
${epic.desired_outcome || '_Not yet defined_'}

### 2.2 Success Metrics
${epic.success_metrics || '_Not yet defined_'}

### 2.3 Key Results
${epic.key_results || '_Not yet defined_'}

---

## 3. Scope

### 3.1 In Scope
${epic.in_scope || '_Not yet defined_'}

### 3.2 Out of Scope
${epic.out_of_scope || '_Not yet defined_'}

---

## 4. Features & Requirements

${featuresList.length > 0 ? featuresList.map((feature, index) => `
### 4.${index + 1} ${feature.title}

**Description**: ${feature.description || '_No description_'}

**Status**: ${feature.stage || 'Draft'}

**Acceptance Criteria**:
${feature.acceptance_criteria || '_Not yet defined_'}

**User Story**:
${feature.user_story || '_Not yet defined_'}
`).join('\n') : '_No features defined yet_'}

---

## 5. Constraints & Assumptions

### 5.1 Constraints
${epic.constraints || '_Not yet defined_'}

### 5.2 Assumptions
${epic.assumptions || '_Not yet defined_'}

### 5.3 Dependencies
${epic.dependencies || '_Not yet defined_'}

---

## 6. Timeline & Milestones

### 6.1 Estimated Timeline
${epic.estimated_timeline || '_Not yet defined_'}

### 6.2 Milestones
${epic.milestones || '_Not yet defined_'}

---

## 7. Risks & Mitigations

${epic.risks || '_Not yet defined_'}

---

## 8. Approval & Sign-off

| Role | Name | Date | Signature |
|------|------|------|-----------|
| Product Owner | | | |
| Tech Lead | | | |
| Stakeholder | | | |

---

*Document generated by JarlPM on ${now}*
`;

    setPrdContent(content);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(prdContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([prdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PRD_${epicData?.title?.replace(/\s+/g, '_') || 'document'}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const completedEpics = epics.filter(e => e.stage === 'completed' || e.stage === 'approved');
  const inProgressEpics = epics.filter(e => e.stage !== 'completed' && e.stage !== 'approved');

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">PRD Generator</h1>
          <p className="text-muted-foreground mt-1">Generate Product Requirements Documents from your epics</p>
        </div>
      </div>

      {/* Epic Selector */}
      <Card className="bg-card border-border">
        <CardContent className="p-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
            <div className="flex-1">
              <label className="text-sm font-medium text-foreground mb-2 block">
                Select an Epic
              </label>
              <Select value={selectedEpic} onValueChange={setSelectedEpic}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Choose an epic to generate PRD" />
                </SelectTrigger>
                <SelectContent>
                  {completedEpics.length > 0 && (
                    <>
                      <div className="px-2 py-1.5 text-xs font-semibold text-muted-foreground">
                        Completed Epics
                      </div>
                      {completedEpics.map((epic) => (
                        <SelectItem key={epic.epic_id} value={epic.epic_id}>
                          <div className="flex items-center gap-2">
                            <Check className="h-3 w-3 text-green-500" />
                            {epic.title}
                          </div>
                        </SelectItem>
                      ))}
                    </>
                  )}
                  {inProgressEpics.length > 0 && (
                    <>
                      <div className="px-2 py-1.5 text-xs font-semibold text-muted-foreground">
                        In Progress
                      </div>
                      {inProgressEpics.map((epic) => (
                        <SelectItem key={epic.epic_id} value={epic.epic_id}>
                          {epic.title}
                        </SelectItem>
                      ))}
                    </>
                  )}
                </SelectContent>
              </Select>
            </div>
            {selectedEpic && (
              <div className="flex gap-2">
                <Button variant="outline" onClick={loadEpicData}>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Refresh
                </Button>
                <Button variant="outline" onClick={handleCopy}>
                  {copied ? (
                    <Check className="h-4 w-4 mr-2" />
                  ) : (
                    <Copy className="h-4 w-4 mr-2" />
                  )}
                  {copied ? 'Copied!' : 'Copy'}
                </Button>
                <Button onClick={handleDownload}>
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* PRD Content */}
      {loading && selectedEpic ? (
        <div className="flex justify-center py-20">
          <Loader2 className="h-8 w-8 text-primary animate-spin" />
        </div>
      ) : selectedEpic && prdContent ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Preview Panel */}
          <div className="lg:col-span-2">
            <Card className="bg-card border-border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  PRD Preview
                </CardTitle>
                <CardDescription>
                  Review and download your generated PRD
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-[600px] w-full rounded-lg border border-border p-4 bg-muted/30">
                  <pre className="text-sm text-foreground whitespace-pre-wrap font-mono">
                    {prdContent}
                  </pre>
                </ScrollArea>
              </CardContent>
            </Card>
          </div>

          {/* Summary Panel */}
          <div className="space-y-4">
            <Card className="bg-card border-border">
              <CardHeader>
                <CardTitle className="text-lg">Document Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <p className="text-sm text-muted-foreground">Epic</p>
                  <p className="font-medium text-foreground">{epicData?.title}</p>
                </div>
                <Separator />
                <div>
                  <p className="text-sm text-muted-foreground">Status</p>
                  <Badge variant="outline" className="mt-1">
                    {epicData?.stage?.replace('_', ' ') || 'Draft'}
                  </Badge>
                </div>
                <Separator />
                <div>
                  <p className="text-sm text-muted-foreground">Features</p>
                  <p className="font-medium text-foreground">{features.length} features</p>
                </div>
                <Separator />
                <div>
                  <p className="text-sm text-muted-foreground">Word Count</p>
                  <p className="font-medium text-foreground">
                    ~{prdContent.split(/\s+/).length} words
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card border-border">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-yellow-500" />
                  Tips
                </CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground space-y-2">
                <p>• Complete all epic fields for a comprehensive PRD</p>
                <p>• Add acceptance criteria to features for better specs</p>
                <p>• Review and customize the generated content</p>
                <p>• Export as Markdown for easy sharing</p>
              </CardContent>
            </Card>
          </div>
        </div>
      ) : (
        <Card className="bg-card border-border">
          <CardContent className="p-12 text-center">
            <BookOpen className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-xl font-medium text-foreground mb-2">
              Select an Epic to Generate PRD
            </h3>
            <p className="text-muted-foreground mb-6 max-w-md mx-auto">
              Choose an epic from the dropdown above to automatically generate a 
              comprehensive Product Requirements Document.
            </p>
            {epics.length === 0 && !loading && (
              <Button onClick={() => navigate('/dashboard')}>
                Create Your First Epic
              </Button>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default PRDGenerator;
