import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { 
  Loader2, FileText, Download, Copy, Check, RefreshCw,
  Plus, ArrowLeft, Calendar, Edit3, Trash2, Save
} from 'lucide-react';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { epicAPI, featureAPI, prdAPI } from '@/api';
import PageHeader from '@/components/PageHeader';
import EmptyState from '@/components/EmptyState';

const PRDGenerator = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [loading, setLoading] = useState(true);
  const [prdList, setPrdList] = useState([]);
  const [availableEpics, setAvailableEpics] = useState([]);
  
  // Editor state
  const [view, setView] = useState('list'); // list | editor
  const [selectedEpicId, setSelectedEpicId] = useState('');
  const [selectedEpicTitle, setSelectedEpicTitle] = useState('');
  const [prdContent, setPrdContent] = useState('');
  const [lastSavedContent, setLastSavedContent] = useState('');
  const [lastSavedAt, setLastSavedAt] = useState(null);
  const [wasAutoGenerated, setWasAutoGenerated] = useState(false);
  const [hasExistingPRD, setHasExistingPRD] = useState(false);
  const [loadingPRD, setLoadingPRD] = useState(false);
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  
  // Create new dialog
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [newPRDEpic, setNewPRDEpic] = useState('');

  useEffect(() => {
    loadData();
  }, []);
  
  // Handle URL parameters for deep linking
  useEffect(() => {
    const epicParam = searchParams.get('epic');
    const createParam = searchParams.get('create');
    
    if (epicParam && !loading) {
      // Deep link to specific epic's PRD
      const existingPRD = prdList.find(p => p.epic_id === epicParam);
      if (existingPRD) {
        // Open existing PRD
        openPRD(epicParam, existingPRD.epic_title);
      } else if (createParam === 'true') {
        // Open in create mode for this epic
        openPRD(epicParam, '');
      }
      // Clear the URL params after handling
      navigate('/prd', { replace: true });
    }
  }, [searchParams, loading, prdList]);

  const loadData = async () => {
    setLoading(true);
    try {
      const [prdRes, epicsRes] = await Promise.all([
        prdAPI.list(),
        prdAPI.getEpicsWithoutPRD()
      ]);
      setPrdList(prdRes.data?.prds || []);
      setAvailableEpics(epicsRes.data?.epics || []);
    } catch (error) {
      console.error('Failed to load data:', error);
      toast.error('Failed to load PRDs');
    } finally {
      setLoading(false);
    }
  };

  const generatePRDContent = (epic, featuresList) => {
    const now = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', month: 'long', day: 'numeric' 
    });

    return `# Product Requirements Document (PRD)

## Document Information
- **Product**: ${epic.title}
- **Version**: 1.0
- **Date**: ${now}
- **Status**: ${epic.stage?.replace('_', ' ').toUpperCase() || 'DRAFT'}

---

## 1. Executive Summary

### 1.1 Problem Statement
${epic.problem_statement || '_Not yet defined_'}

### 1.2 Product Vision
${epic.vision || '_Not yet defined_'}

### 1.3 Target Users
${epic.target_users || '_Not yet defined_'}

---

## 2. Goals & Objectives

### 2.1 Desired Outcomes
${epic.desired_outcome || '_Not yet defined_'}

### 2.2 Success Metrics
${epic.success_metrics || '_Not yet defined_'}

### 2.3 Key Results
${epic.key_results || '_Not yet defined_'}

---

## 3. Scope

### 3.1 In Scope
${epic.in_scope || '_Not yet defined_'}

### 3.2 Out of Scope
${epic.out_of_scope || '_Not yet defined_'}

---

## 4. Features & Requirements

${featuresList.length > 0 ? featuresList.map((feature, index) => `
### 4.${index + 1} ${feature.title}

**Description**: ${feature.description || '_No description_'}

**Status**: ${feature.stage || 'Draft'}

**Acceptance Criteria**:
${feature.acceptance_criteria || '_Not yet defined_'}

**User Story**:
${feature.user_story || '_Not yet defined_'}
`).join('\n') : '_No features defined yet_'}

---

## 5. Constraints & Assumptions

### 5.1 Constraints
${epic.constraints || '_Not yet defined_'}

### 5.2 Assumptions
${epic.assumptions || '_Not yet defined_'}

### 5.3 Dependencies
${epic.dependencies || '_Not yet defined_'}

---

## 6. Timeline & Milestones

### 6.1 Estimated Timeline
${epic.estimated_timeline || '_Not yet defined_'}

### 6.2 Milestones
${epic.milestones || '_Not yet defined_'}

---

## 7. Risks & Mitigations

${epic.risks || '_Not yet defined_'}

---

## 8. Approval & Sign-off

| Role | Name | Date | Signature |
|------|------|------|-----------|
| Product Owner | | | |
| Tech Lead | | | |
| Stakeholder | | | |

---

*Document generated by JarlPM on ${now}*
`;
  };

  const openPRD = async (epicId, epicTitle) => {
    setSelectedEpicId(epicId);
    setSelectedEpicTitle(epicTitle);
    setLoadingPRD(true);
    setView('editor');
    
    try {
      const response = await prdAPI.get(epicId);
      const data = response.data;
      
      if (data.exists && data.prd) {
        setPrdContent(data.prd.content);
        setLastSavedContent(data.prd.content);
        setLastSavedAt(data.updated_at ? new Date(data.updated_at) : new Date());
        setWasAutoGenerated(false);
        setHasExistingPRD(true);
      } else {
        // Generate from epic data
        const [epicRes, featuresRes] = await Promise.all([
          epicAPI.get(epicId),
          featureAPI.listForEpic(epicId)
        ]);
        const content = generatePRDContent(epicRes.data, featuresRes.data || []);
        setPrdContent(content);
        setLastSavedContent(content);
        setLastSavedAt(null);
        setWasAutoGenerated(true);
        setHasExistingPRD(false);
      }
    } catch (error) {
      console.error('Failed to load PRD:', error);
      setPrdContent('');
      setHasExistingPRD(false);
    } finally {
      setLoadingPRD(false);
    }
  };

  const createNewPRD = async () => {
    if (!newPRDEpic) {
      toast.error('Please select an epic');
      return;
    }
    
    const epic = availableEpics.find(e => e.epic_id === newPRDEpic);
    setShowCreateDialog(false);
    setNewPRDEpic('');
    
    await openPRD(newPRDEpic, epic?.title || 'New PRD');
  };

  const backToList = () => {
    setView('list');
    setSelectedEpicId('');
    setSelectedEpicTitle('');
    setPrdContent('');
    setHasExistingPRD(false);
    loadData();
  };

  const handleSave = async () => {
    if (!selectedEpicId) return;
    
    setSaving(true);
    try {
      await prdAPI.save(selectedEpicId, prdContent, selectedEpicTitle);
      setHasExistingPRD(true);
      setWasAutoGenerated(false);
      setLastSavedContent(prdContent);
      setLastSavedAt(new Date());
      toast.success('PRD saved!');
    } catch (error) {
      console.error('Failed to save PRD:', error);
      toast.error('Failed to save PRD');
    } finally {
      setSaving(false);
    }
  };

  const handleRegenerate = async () => {
    if (!selectedEpicId) return;
    
    setLoadingPRD(true);
    try {
      // Use AI to generate a comprehensive PRD
      const response = await prdAPI.generate(selectedEpicId);
      if (response.data.success && response.data.content) {
        setPrdContent(response.data.content);
        setWasAutoGenerated(true);
        toast.success('PRD regenerated with AI!');
      } else {
        throw new Error(response.data.message || 'Failed to generate PRD');
      }
    } catch (error) {
      console.error('Failed to regenerate:', error);
      const errorMsg = error.response?.data?.detail || error.message || 'Failed to regenerate PRD';
      if (error.response?.status === 402) {
        toast.error('Active subscription required for AI features');
      } else if (error.response?.status === 400 && errorMsg.includes('LLM')) {
        toast.error('Please configure your LLM provider in Settings');
      } else {
        toast.error(errorMsg);
      }
    } finally {
      setLoadingPRD(false);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(prdContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy');
    }
  };

  const handleDownload = () => {
    const blob = new Blob([prdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PRD_${selectedEpicTitle.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric'
    });
  };

  // LIST VIEW
  if (view === 'list') {
    return (
      <div className="p-6 space-y-6">
        <PageHeader
          title="PRDs"
          description="Product requirements documents for your epics."
          actions={
            <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
              <DialogTrigger asChild>
                <Button disabled={availableEpics.length === 0} data-testid="create-new-prd">
                  <Plus className="h-4 w-4 mr-2" />
                  Create PRD
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create New PRD</DialogTitle>
                  <DialogDescription>
                    Select an epic to create a PRD for.
                  </DialogDescription>
                </DialogHeader>
                <div className="py-4">
                  <Select value={newPRDEpic} onValueChange={setNewPRDEpic}>
                    <SelectTrigger data-testid="select-epic-for-prd">
                      <SelectValue placeholder="Select an epic..." />
                    </SelectTrigger>
                    <SelectContent>
                      {availableEpics.map((epic) => (
                        <SelectItem key={epic.epic_id} value={epic.epic_id}>
                          {epic.title}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {availableEpics.length === 0 && (
                    <p className="text-sm text-muted-foreground mt-2">
                      All epics already have a PRD.
                    </p>
                  )}
                </div>
                <DialogFooter>
                  <Button variant="outline" onClick={() => setShowCreateDialog(false)}>Cancel</Button>
                  <Button onClick={createNewPRD} disabled={!newPRDEpic}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          }
        />

        {/* duplicate create dialog removed */}

        {/* end removed duplicate dialog */}

        {loading ? (
          <div className="flex justify-center py-20">
            <Loader2 className="h-8 w-8 text-primary animate-spin" />
          </div>
        ) : prdList.length === 0 ? (
          <EmptyState
            icon={FileText}
            title="No PRDs yet"
            description={
              availableEpics.length > 0
                ? 'Create a PRD to capture requirements, scope, and acceptance criteria.'
                : 'Create an Epic first, then generate a PRD from it.'
            }
            actionLabel={availableEpics.length > 0 ? 'Create PRD' : 'Go to Dashboard'}
            onAction={() => (availableEpics.length > 0 ? setShowCreateDialog(true) : navigate('/dashboard'))}
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {prdList.map((item) => (
              <Card 
                key={item.prd_id} 
                className="bg-card border-border hover:border-primary/50 cursor-pointer transition-colors"
                onClick={() => openPRD(item.epic_id, item.epic_title)}
                data-testid={`prd-card-${item.epic_id}`}
              >
                <CardHeader className="pb-2">
                  <div className="flex items-start justify-between">
                    <CardTitle className="text-lg">{item.epic_title}</CardTitle>
                    <Badge variant="outline" className={
                      item.status === 'approved' ? 'bg-green-500/10 text-green-500' :
                      item.status === 'review' ? 'bg-yellow-500/10 text-yellow-500' :
                      ''
                    }>
                      {item.status || 'draft'}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <div className="flex items-center gap-1">
                      <Calendar className="h-4 w-4" />
                      {formatDate(item.updated_at)}
                    </div>
                    <span>v{item.version}</span>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    );
  }

  // EDITOR VIEW
  const isDirty = prdContent !== lastSavedContent;
  const lastSavedLabel = lastSavedAt
    ? `Last saved ${lastSavedAt.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}`
    : null;

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <PageHeader
        title={selectedEpicTitle}
        description={
          <span className="inline-flex items-center gap-2">
            <span>Product Requirements Document</span>
            {lastSavedLabel ? <span className="text-muted-foreground">• {lastSavedLabel}</span> : null}
            {isDirty ? (
              <Badge variant="outline" className="border-amber-500/30 text-amber-600 bg-amber-500/5">Unsaved</Badge>
            ) : hasExistingPRD ? (
              <Badge variant="outline" className="bg-emerald-500/10 text-emerald-600 border-emerald-500/30">Saved</Badge>
            ) : (
              <Badge variant="outline" className="bg-muted">Draft</Badge>
            )}
          </span>
        }
        actions={
          <>
            <Button variant="ghost" onClick={backToList} className="gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
            <Button variant="outline" onClick={handleRegenerate} disabled={loadingPRD} className="gap-2">
              <RefreshCw className={loadingPRD ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />
              {loadingPRD ? 'Generating...' : 'Regenerate with AI'}
            </Button>
            <Button variant="outline" onClick={handleCopy} className="gap-2">
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? 'Copied' : 'Copy'}
            </Button>
            <Button variant="outline" onClick={handleDownload} className="gap-2">
              <Download className="h-4 w-4" />
              Download
            </Button>
            <Button onClick={handleSave} disabled={saving || loadingPRD} className="gap-2">
              {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              {hasExistingPRD ? 'Update' : 'Save'}
            </Button>
          </>
        }
      />

      {wasAutoGenerated && (
        <Card className="border-amber-500/30 bg-amber-500/5">
          <CardContent className="py-4">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="font-medium">Auto-generated draft</div>
                <div className="text-sm text-muted-foreground mt-1">
                  This PRD was generated from your Epic + Features. Review and edit before sharing.
                </div>
              </div>
              <Badge variant="outline" className="border-amber-500/30 text-amber-600">Draft</Badge>
            </div>
          </CardContent>
        </Card>
      )}

      {/* PRD Content */}
      {loadingPRD ? (
        <div className="flex justify-center py-20">
          <Loader2 className="h-8 w-8 text-primary animate-spin" />
        </div>
      ) : (
        <Card className="bg-card border-border">
          <CardContent className="p-0">
            <Tabs defaultValue="edit" className="w-full">
              <div className="border-b border-border px-4">
                <TabsList className="h-12 bg-transparent">
                  <TabsTrigger value="edit" className="data-[state=active]:bg-muted">
                    <Edit3 className="h-4 w-4 mr-2" />
                    Edit
                  </TabsTrigger>
                  <TabsTrigger value="preview" className="data-[state=active]:bg-muted">
                    <FileText className="h-4 w-4 mr-2" />
                    Preview
                  </TabsTrigger>
                </TabsList>
              </div>
              
              <TabsContent value="edit" className="m-0">
                <Textarea
                  value={prdContent}
                  onChange={(e) => setPrdContent(e.target.value)}
                  className="min-h-[600px] border-0 rounded-none font-mono text-sm resize-none focus-visible:ring-0"
                  placeholder="PRD content will appear here..."
                />
              </TabsContent>
              
              <TabsContent value="preview" className="m-0">
                <ScrollArea className="h-[600px]">
                  <div className="p-6">
                    <div className="text-sm leading-6 space-y-4">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {prdContent || ''}
                      </ReactMarkdown>
                    </div>
                  </div>
                </ScrollArea>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default PRDGenerator;
